config/routes.rb
Rails.application.routes.draw do

  resources :payment_profiles
  post 'payment_profiles/switch_plan/:id' => 'payment_profiles#switch_plan', as: "switch_plan"
  post 'payment_profiles/add_card/:id' => 'payment_profiles#add_card', as: "add_card"
  post 'payment_profiles/remove_card/:id/:fingerprint' => 'payment_profiles#remove_card', as: "remove_card"
  post 'payment_profiles/set_default_card/:id' => 'payment_profiles#set_default_card', as: "set_default_card"

  resources :plans
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users
  get '/' => 'static_pages#home', as: 'root'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
end

app/models/payment_profile.rb
class PaymentProfile < ApplicationRecord
  belongs_to :user
  validates :user_id, uniqueness: true
end

app/controllers/payment_profiles_controller.rb
class PaymentProfilesController < ApplicationController
  before_action :set_payment_profile, only: [:show, :edit, :update, :destroy, :switch_plan, :add_card, :remove_card, :set_default_card]

  def index
    @payment_profiles = PaymentProfile.all
    authorize PaymentProfile
  end

  def show
    authorize @payment_profile
    customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'show'
      return
    end

    @charges = []
    Charge.where(:user_id => current_user.id).each do |c|
      stripe_charge = FetchStripeCharge.call(@payment_profile.user, c.charge_stripe_id)
      if @payment_profile.user.payment_profile.errors.any?
        render 'show'
        return
      end
      @charges << stripe_charge
    end

    @invoices = []

    Invoice.where(:user_id => current_user.id).each do |c|
      stripe_invoice = FetchStripeInvoice.call(@payment_profile.user, c.invoice_stripe_id)
      if @payment_profile.user.payment_profile.errors.any?
        render 'show'
        return
      end
      @invoices << stripe_invoice
    end

    @invoices = @invoices.compact

  end

  def new
    @payment_profile = PaymentProfile.new
  end

  def edit
    authorize @payment_profile
    customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    # Sync Plan With Stripe
    customer.subscriptions.each do |s|
      sub = current_user.subscriptions.find_by_stripe_id(s.id)
      plan = Plan.find_by_stripe_id(s.plan.id)
      if !sub
        subscription = Subscription.new(plan_id: plan.id, user_id: current_user.id, stripe_id: s.id)
        subscription.save!
      else
        sub.plan_id = plan.id
        sub.save!
      end
    end
    # Sync Plan With Stripe

    @cards = []

    @default_card = customer.default_source
    @cards = customer.sources
  end

  def create
    @payment_profile = PaymentProfile.new(payment_profile_params)
    respond_to do |format|
      if @payment_profile.save
        format.html { redirect_to @payment_profile, notice: 'Payment profile was successfully created.' }
        format.json { render :show, status: :created, location: @payment_profile }
      else
        format.html { render :new }
        format.json { render json: @payment_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment_profile.update(payment_profile_params)
        format.html { redirect_to @payment_profile, notice: 'Payment profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_profile }
      else
        format.html { render :edit }
        format.json { render json: @payment_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment_profile.destroy
    respond_to do |format|
      format.html { redirect_to payment_profiles_url, notice: 'Payment profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def switch_plan
    stripe_customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end
    ChangePlan.call(@payment_profile.user, stripe_customer, params[:stripe_subscription_id], params[:from_plan], params[:plan_id])
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end
    subscription = current_user.subscriptions.find_by_stripe_id(params[:stripe_subscription_id])
    if subscription
      subscription.plan = Plan.find_by_stripe_id(params[:plan_id])
      subscription.save!
    end
    redirect_to edit_payment_profile_path(current_user.payment_profile.id)
  end

  def add_card

    stripe_customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    AddCardToStripeCustomer.call(@payment_profile.user, stripe_customer, params[:stripeToken])
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    flash[:notice] = 'Successfully added card.'

    redirect_to edit_payment_profile_path(current_user.payment_profile.id)
  end

  def remove_card
    stripe_customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    RemoveCardFromStripeCustomer.call(@payment_profile.user, stripe_customer, params[:fingerprint])
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    if stripe_customer.sources.count == 0
      NoCardsSoDowngradeToFreePlans.call(@payment_profile.user, stripe_customer)
      if @payment_profile.user.payment_profile.errors.any?
        render 'edit'
        return
      end
      current_user.subscriptions.each do |s|
        if s
          s.plan = Plan.find_by_stripe_id('starter_plan')
          s.save!
        end
      end
    end

    flash[:notice] = 'Successfully deleted card.'

    redirect_to edit_payment_profile_path(current_user.payment_profile.id)
  end

  def set_default_card

    stripe_customer = FetchStripeCustomer.call(@payment_profile.user)
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    SetDefaultCardForStripeCustomer.call(@payment_profile.user, stripe_customer, params[:fingerprint])
    if @payment_profile.user.payment_profile.errors.any?
      render 'edit'
      return
    end

    flash[:notice] = 'Successfully set card as default.'
    redirect_to edit_payment_profile_path(current_user.payment_profile.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_profile
      @payment_profile = PaymentProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_profile_params
      params.fetch(:payment_profile, {})
    end
end

app/helpers/payment_profiles_helper.rb
module PaymentProfilesHelper
end

app/views/payment_profiles/_credit_card.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <br/>
    <h2 class="text-center">Card Info </h2>
    <br/>
    <p class="text-center">You currently have <%= pluralize(!@cards ? 0 : @cards.count, "card") %> on file with us: </p>
  </div>

  <% if @cards %>
    <% @cards.each.with_index do |c, i| %>
      <div id='individual-card-info' class="col-md-10 col-md-offset-1 well">

        <p style="font-size: 10px;">
          <% if (c.id == @default_card) %>
            *Default Card*
          <% else %>
            <%= link_to 'Set As Default', set_default_card_path(:id => @payment_profile.id, :fingerprint => c.fingerprint), :id => "set_default_card",  :method => 'post' %>
          <% end %>
        </p>

        <%= image_tag("credit-card-icon.png", :size => "30x30", alt: "Credit Card Icon") %>
        <div>
          <label class="control-label">Expiration Date (MM/YYYY): </label>
          <br/>
          <%= c.exp_month %>
          <span> / </span>
          <%= c.exp_year %>
        </div>
        <label class="control-label">Last 4 Digits: </label>
        <div class="form-group">
          **** **** **** <%= c.last4 %>
        </div>

        <%= link_to 'Remove Card', remove_card_path(:id => @payment_profile.id, :fingerprint => c.fingerprint), :id => "remove_card",  :method => 'post', :data => { :confirm => 'Are you sure you want to remove this card?' } %>

        <% if @cards.count == 1 %>
          <p style="font-size: 10px;">Removing all cards will place you on our starter plan (which is free).</p>
        <% end %>

      </div>
    <% end %>
  <% end %>
</div>

<div class="row">
  <button type="button" class="col-xs-8 col-xs-offset-2 btn btn-info btn-extra-round" data-toggle="collapse" data-target="#add-credit-card-form">+ Add a card +</button>
  <br/>
  <div>
    <br/>
    <div id="add-credit-card-form" class="col-md-10 col-md-offset-1 well collapse">

      <%= form_tag(add_card_path, :id => "add_card_form") do %>

        <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 well">
            <h3 class="text-center">Card Details</h3>
            <h4 class="text-center payment-errors"></h4>
            <div class='form-group'>
                <label class="control-label" for="number">Card Number</label>
                <input type="text" style="margin: 0 auto; width: 16em;" size="20" data-stripe="number" placeholder="**** **** **** ****" pattern="[\d ]*"/>
            </div>

            <div class="form-group">
              <label class="control-label" for="cvc">CVC</label>
              <input type="text" style="margin: 0 auto; width: 3em;" size="3" data-stripe="cvc" id="cvc" placeholder="***" pattern="\d*"/>
              <%= image_tag("credit-card-icon.png", :size => "30x30", alt: "Credit Card Icon") %>
            </div>

            <div class="form-group">
              <label class="control-label">Exp (MM/YYYY)</label>
              <br/>
              <input type="text" size="2" id="exp-month" data-stripe="exp-month" placeholder="MM" pattern="\d*" style="width: 4em"/>
              <span> / </span>
              <input type="text" size="4" id="exp-year" data-stripe="exp-year" placeholder="YYYY" pattern="\d*" style="width: 8em"/>
            </div>

        </div>

        <div class='form-row'>
          <div class='col-md-12 form-group'>
            <button class='form-control btn btn-primary submit-button' type='submit'>Submit Card Details</button>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_z3yrL4LC2PGjjgjDRnfim1DK');
</script>

app/views/payment_profiles/_plans.html.erb
<br/>
<h3>You are currently subscribed to <%= pluralize(@payment_profile.user.subscriptions ? 1 : 0, "service") %>:</h3>
<br/>

<% @payment_profile.user.subscriptions.each do |s| %>
  <%= form_tag(switch_plan_path(@payment_profile.id), class:"well") do %>
    <p>You are subscribed to the <i><%= s.plan.name %></i></p>

    <%= hidden_field_tag 'from_plan', s.plan.stripe_id %>
    <%= hidden_field_tag 'stripe_subscription_id', s.stripe_id %>
    <div class="field">
      <%= collection_select( nil, :plan_id, Plan.all.order(:amount), :stripe_id, :name, {:selected => s.plan.stripe_id, :prompt => true}, {class: 'form-control'}) %>
      <%= submit_tag "Switch Plan", class: "btn btn-primary form-control" %>
    </div>
  <% end %>
<% end %>
<br />

app/views/payment_profiles/edit.html.erb
<h2>Edit Payment Details</h2>

<hr class="col-md-10 col-md-offset-1"></hr>

<div class="row">
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to "Profile", edit_user_registration_path %></li>
    <li role="presentation" class="active"><%= link_to "Payment", edit_payment_profile_path(current_user.payment_profile.id) %></li>
    <li role="presentation"><%= link_to "Billing", payment_profile_path(current_user.payment_profile.id) %></li>
  </ul>

  <div class="col-md-6 col-md-offset-3">

      <br/>
      <% if @payment_profile.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@payment_profile.errors.count, "error") %> occurred:</h2>
          <ul>
          <% @payment_profile.errors.full_messages.each do |message, | %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= render partial: 'plans' %>
      <%= render partial: 'credit_card' %>

  </div>

</div>

app/views/payment_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_profiles.each do |payment_profile| %>
      <tr>
        <td><%= link_to 'Show', payment_profile %></td>
        <td><%= link_to 'Edit', edit_payment_profile_path(payment_profile) %></td>
        <td><%= link_to 'Destroy', payment_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/payment_profiles/show.html.erb
<h2>View Billing Details</h2>

<hr class="col-md-10 col-md-offset-1"></hr>

<div class="row">
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to "Profile", edit_user_registration_path %></li>
    <li role="presentation"><%= link_to "Payment", edit_payment_profile_path(current_user.payment_profile.id) %></li>
    <li role="presentation" class="active"><%= link_to "Billing", payment_profile_path(current_user.payment_profile.id) %></li>
  </ul>

  <div class="col-md-6 col-md-offset-3">

    <h2 class="text-center"></h2>
    <br/>
    <% if @payment_profile.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@payment_profile.errors.count, "error") %> occurred:</h2>
        <ul>
        <% @payment_profile.errors.full_messages.each do |message, | %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p>

      <h3 class="text-center" style="letter-spacing: 4px;"><!-- Charges --></h3>
        <table>
          <tr style="letter-spacing: 2px; text-shadow: 1px 1px #000000;">
            <th class="charges">Amount</th>
            <th class="charges">Card Number</th>
            <th class="charges">Date Of Charge</th>
          </tr>
          <% @charges.each do |s| %>
              <tr>
                <td><%= Money.new(s.amount, s.currency).format %></td>
                <td>(last digits) <%= s.source.last4 %></td>
                <td><%= DateTime.strptime(s.created.to_s,'%s').to_date %></td>
              </tr>
          <% end %>
        </table>
    </p>

    <p>
      <h3 class="text-center" style="letter-spacing: 4px;"><!-- Invoices --></h3>

        <table>
          <tr style="letter-spacing: 2px; text-shadow: 1px 1px #000000;">
            <th class="invoices">Amount Due</th>
            <th class="invoices">Date Of Invoice</th>
          </tr>

          <% @invoices.each do |s| %>
              <tr>
                <td><%= Money.new(s.total, s.currency).format %></td>
                <td><%= DateTime.strptime(s.date.to_s,'%s').to_date %></td>
              </tr>
          <% end %>
        </table>
    </p>

  </div>

</div>