config/routes.rb
Rails.application.routes.draw do

  resources :payment_profiles
  post 'payment_profiles/switch_plan/:id' => 'payment_profiles#switch_plan', as: "switch_plan"
  post 'payment_profiles/add_card/:id' => 'payment_profiles#add_card', as: "add_card"
  post 'payment_profiles/remove_card/:id/:fingerprint' => 'payment_profiles#remove_card', as: "remove_card"
  post 'payment_profiles/set_default_card/:id' => 'payment_profiles#set_default_card', as: "set_default_card"

  resources :plans
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users
  get '/' => 'static_pages#home', as: 'root'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if (message_type == "timedout") %>
    <div class="alert alert-warning">
      Session Expired
      <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
  <% elsif (message_type == "alert") %>
    <div class="alert alert-danger">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
  <% elsif (message_type == "notice") %>
    <div class="alert alert-info">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
  <% else %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= link_to image_tag("rushlightlogo.png", :size => "30x15", alt: "Rushlight Logo") %>
  <small>
    LightVest &copy <%= DateTime.now.year %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "LightVest", root_path, id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">


        <% if user_signed_in? %>
          <!-- <li><%= link_to "Users", users_path %></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LightVest</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>